### ISSUE TITLE
Dimensions not defined error in GameLoop Component

### ISSUE THREAD

**Issue by jacquestvanzuydam** [bberak/react-game-engine#1]
I'm guessing this is left over from the React Native version.

**Comment by bberak** [comment]
Oh dear.. Nice find @jacquestvanzuydam 

Also, just for kicks, what is your use-case for using the `GameLoop` component over the `GameEngine`?

I'll get this fixed.

**Comment by bberak** [comment]
@jacquestvanzuydam - I've just released `react-game-engine@0.1.1` that fixes this issue.

Cheers!
