### ISSUE TITLE
Finger

### ISSUE THREAD

**Issue by AndreuSCK** [bberak/react-game-engine#6]
@Hey, I wanted to try a bit, and copied the text of the finger game, in the main homepage in https://www.npmjs.com/package/react-game-engine

index.js, renderers and systems, all with the text you have there, and it doesnt show anything when i do npm start x.x

edit: and something in the sintaxis is wrong in renderers.js, in the finger div, you start with 

div style={{  -- and finish with }]} />

**Comment by bberak** [comment]
Hi @AndreuSCK,

Sorry, the docs are terrible :/

I'm going to clean them up, but have some work to do on the React Native version before I can get to this.

You can try follow the documentation updates in this comment: https://github.com/bberak/react-game-engine/issues/2#issuecomment-553731909

Or you can take a look at https://github.com/bberak/react-game-engine-template to get up and running quickly with a project you can play around with.

**Comment by bberak** [comment]
Hi @AndreuSCK , I've updated the README. Cheers.
